[project]
name = "polars-dq-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "ipykernel>=6.30.0",
    "polars>=1.30.0",
    "rich>=14.0.0",
    "typer>=0.16.0",
]
